name: deneme2
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"  # Dart SDK sürüm kısıtlaması

dependencies:
  flutter:
    sdk: flutter
  url_launcher : ^6.2.2

  cupertino_icons: ^1.0.2
  http: ^1.1.2
  dio: ^4.0.0  # Dio paketi

  # Firebase paketleri
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  firebase_analytics: ^10.7.4
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
