// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGagrUbfoB2Ztk1IYB7d1xZDY9dAx-YCo',
    appId: '1:897949585313:web:d8b0826d225e5b1806c5e0',
    messagingSenderId: '897949585313',
    projectId: 'flutterlogin-976c3',
    authDomain: 'flutterlogin-976c3.firebaseapp.com',
    storageBucket: 'flutterlogin-976c3.appspot.com',
    measurementId: 'G-DJJC7VLKSB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbl5Wz0xAyEw1uORR8d_Pw5uegg5NuaC0',
    appId: '1:897949585313:android:36be084ab280140006c5e0',
    messagingSenderId: '897949585313',
    projectId: 'flutterlogin-976c3',
    storageBucket: 'flutterlogin-976c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJYWD_RDT0Vk-Xn_aMdowv9-u9U1r8VEg',
    appId: '1:897949585313:ios:b619be1f7875037006c5e0',
    messagingSenderId: '897949585313',
    projectId: 'flutterlogin-976c3',
    storageBucket: 'flutterlogin-976c3.appspot.com',
    iosBundleId: 'com.example.deneme2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJYWD_RDT0Vk-Xn_aMdowv9-u9U1r8VEg',
    appId: '1:897949585313:ios:0e9a902cfead0cad06c5e0',
    messagingSenderId: '897949585313',
    projectId: 'flutterlogin-976c3',
    storageBucket: 'flutterlogin-976c3.appspot.com',
    iosBundleId: 'com.example.deneme2.RunnerTests',
  );
}
